apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{.Values.component}}-vsvc
  namespace: {{.Values.namespace}}
spec:
  hosts:
    - "{{.Values.component}}.{{.Values.externalDomain}}"
  gateways:
    - {{.Values.gatewayName}}.svc.cluster.local
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number:  {{.Values.containerPort}}
            host: {{.Values.component}}