{{- if semverCompare ">=1.16.0-0" .Values.Caps.KubeVersion.Version }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  namespace: {{.Values.namespace}}
  name:  {{.Values.component}}-ingress
  annotations:
    external-dns.alpha.kubernetes.io/target: {{.Values.ingressDomain}}
spec:
  rules:
    - host: {{.Values.component}}.{{.Values.externalDomain}}