replicas: 1
port: 9090
containerPort: 9090
resources:
  limits:
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 1Gi
promVersion: v2.12.0
paused: false
retention: "5d"
volumesEncryption: false
diskSize: 25Gi
elbAccessLoggingEnabled: False
logLevel: "info"
serviceMonitorNamespaceSelector: false # means only look into this .namespace for sm's
serviceMonitorSelector: false # means
podMonitorNamespaceSelector: false
podMonitorSelector: false

ruleNamespaceSelector: false # means only rules from this .namespace
alertManagerNamespace: kube-system
matchLabels:
  role: alert-rules
  prometheus: monitoring
layer: base
additionalScrapeConfigs: false
additionalScrapeConfigsOptional: false
istio: True
additionalPodMetadata: false
externalLabels: {}
thanos: false
noReclaim: false
imagePullSecrets: true