 
{{- with .Values }}
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-{{.namespace}}
  namespace: {{.namespace}}
  labels:
    release: {{.release}}
    component:  prometheus-{{.namespace}}
{{ if .rbac }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-{{.namespace}}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- nonResourceURLs: ["*"]
  verbs: ["*"]
{{ end }}
{{ if .rbac }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-{{.namespace}}-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-{{.namespace}}
subjects:
- kind: ServiceAccount
  name: prometheus-{{.namespace}}
  namespace: {{.namespace}}
{{ end }}

  
  
{{- end }}