{
 "title": "K8S State Metrics",
 "description": "Deployment overview for Kubernetes deploys.",
 "tags": [
  "kubernetes",
  "kubernetes-app"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kube_pod_info, host_ip)"
   },
   {
    "name": "Namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "Type",
    "query": "label_values(kube_pod_info{namespace=~\"^$Namespace$\"}, created_by_kind)"
   },
   {
    "name": "Pod",
    "query": "label_values(kube_pod_info{namespace=~\"^$Namespace$\", created_by_kind=~\"^$Type$\"}, pod)"
   },
   {
    "name": "Container",
    "query": "label_values(kube_pod_container_info{namespace=~\"^$Namespace$\", pod=~\"^$Pod$\"}, container)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment Replicas - Desired",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{namespace=~\"$Namespace\",deployment=~\"$Container\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Up-to-date",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$Namespace\",deployment=~\"$Container\"})"
    }
   ]
  },
  {
   "title": "Deployments - Current Set Up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{namespace=~\"$Namespace\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=~\"$Namespace\",deployment=~\"$Container\"})"
    }
   ]
  },
  {
   "title": "Deployments Replicas - Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$Namespace\",deployment=~\"$Container\"})"
    }
   ]
  },
  {
   "title": "StatefulSet Replicas - Desired",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas{namespace=~\"$Namespace\",statefulset=~\"$Container\"})"
    }
   ]
  },
  {
   "title": "StatefulSet Replicas - Updated",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_updated{namespace=~\"$Namespace\",statefulset=~\"$Container\"})"
    }
   ]
  },
  {
   "title": "StatefulSet - Current Set Up",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas{namespace=~\"$Namespace\"}",
     "legendFormat": "{{  statefulset }}"
    }
   ]
  },
  {
   "title": "StatefulSet Replicas - Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas_ready{namespace=~\"$Namespace\",statefulset=~\"$Container\"})"
    }
   ]
  },
  {
   "title": "StatefulSet Replicas - Unavailable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_statefulset_status_replicas{namespace=~\"$Namespace\",statefulset=~\"$Container\"})-sum(kube_statefulset_status_replicas_ready{namespace=~\"$Namespace\",statefulset=~\"$Container\"})"
    }
   ]
  },
  {
   "title": "Container Status Running",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kube_pod_container_status_running{namespace=~\"$Namespace\", container=~\"$Container\", container!=\"istio-proxy\", container!=\"create-kafka-topics\"}"
    }
   ]
  },
  {
   "title": "Container Status Running",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_running{namespace=~\"$Namespace\", container=~\"$Container\", container!=\"istio-proxy\", container!=\"create-kafka-topics\", container!=\"build\", container!=\"helper\", container!=\"svc-0\"}",
     "legendFormat": "{{container}}-{{pod}}"
    }
   ]
  }
 ]
}