name: test-on-push

on: [push, pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Build
        run: make build
      - name: Test
        run: make test
