name: test-master

on:
  push:
    branches:
      - master
      - test
  schedule:
    - cron: '20 13 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Build
        run: docker build -t datareply/korginazer:latest -f Dockerfile .
      - name: Test
        run: make test
